"""Add description and status fields

Revision ID: 387cdff8c832
Revises: 7fea5b09de4f
Create Date: 2024-12-23 16:04:29.933705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387cdff8c832'
down_revision = '7fea5b09de4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
